# fly.toml app configuration file generated for ygh-surl-project-11-dawn-sea-9705 on 2024-11-07T10:29:12+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ygh-surl-project-11-dawn-sea-9705'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
